export interface MenuItem {
  id: string;
  name: string;
  nameEn: string;
  nameUz: string;
  description: string;
  descriptionEn: string;
  descriptionUz: string;
  price: number;
  calories: number;
  image: string;
  category: string;
}

export const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "Салат с грибами фалафель",
    nameEn: "Falafel Mushroom Salad",
    nameUz: "Falafel qo'ziqorin salati",
    description: "Свежий салат с хрустящим фалафелем и грибами",
    descriptionEn: "Fresh salad with crispy falafel and mushrooms",
    descriptionUz: "Qarsildoq falafel va qo'ziqorinli yangi salat",
    price: 56000,
    calories: 320,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    category: "salads",
  },
  {
    id: "2",
    name: "Салат с курицей и авокадо",
    nameEn: "Chicken Avocado Salad",
    nameUz: "Tovuq avokado salati",
    description: "Нежная курица с авокадо и зеленью",
    descriptionEn: "Tender chicken with avocado and greens",
    descriptionUz: "Avokado va ko'katlar bilan yumshoq tovuq",
    price: 58000,
    calories: 380,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    category: "salads",
  },
  {
    id: "3",
    name: "Боул с лососем и рисом",
    nameEn: "Salmon Rice Bowl",
    nameUz: "Losos guruchli boul",
    description: "Свежий лосось с рисом и овощами",
    descriptionEn: "Fresh salmon with rice and vegetables",
    descriptionUz: "Guruch va sabzavotlar bilan yangi losos",
    price: 76000,
    calories: 450,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    category: "bowls",
  },
  {
    id: "4",
    name: "Салат с яйцом и оливками",
    nameEn: "Fish Egg Salad with Olive",
    nameUz: "Zaytunli baliq tuxum salati",
    description: "Классический салат с яйцом и оливками",
    descriptionEn: "Classic salad with egg and olives",
    descriptionUz: "Tuxum va zaytun bilan klassik salat",
    price: 48000,
    calories: 290,
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    category: "salads",
  },
  {
    id: "5",
    name: "Зелёная богиня салат",
    nameEn: "Green Goddess Salad",
    nameUz: "Yashil ma'buda salati",
    description: "Свежие овощи с зелёным соусом",
    descriptionEn: "Fresh vegetables with green goddess dressing",
    descriptionUz: "Yashil sous bilan yangi sabzavotlar",
    price: 45000,
    calories: 250,
    image: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=400&h=300&fit=crop",
    category: "salads",
  },
  {
    id: "6",
    name: "Паста капрезе боул",
    nameEn: "Chicken Caprese Pasta Bowls",
    nameUz: "Tovuq kaprese pasta bouli",
    description: "Паста с курицей, томатами и моцареллой",
    descriptionEn: "Pasta with chicken, tomatoes and mozzarella",
    descriptionUz: "Tovuq, pomidor va mocarella bilan pasta",
    price: 62000,
    calories: 520,
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&h=300&fit=crop",
    category: "bowls",
  },
  {
    id: "7",
    name: "Куриный суп с овощами",
    nameEn: "Chicken Vegetable Soup",
    nameUz: "Sabzavotli tovuq sho'rva",
    description: "Наваристый куриный суп со свежими овощами",
    descriptionEn: "Rich chicken soup with fresh vegetables",
    descriptionUz: "Yangi sabzavotlar bilan boy tovuq sho'rva",
    price: 42000,
    calories: 280,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
    category: "soups",
  },
  {
    id: "8",
    name: "Крем-суп из брокколи",
    nameEn: "Broccoli Cream Soup",
    nameUz: "Brokkoli krem-sho'rva",
    description: "Нежный крем-суп из свежей брокколи",
    descriptionEn: "Smooth cream soup from fresh broccoli",
    descriptionUz: "Yangi brokkolidan yumshoq krem-sho'rva",
    price: 38000,
    calories: 220,
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&h=300&fit=crop",
    category: "soups",
  },
  {
    id: "9",
    name: "Зелёный смузи",
    nameEn: "Green Smoothie",
    nameUz: "Yashil smuzi",
    description: "Витаминный смузи из шпината, яблока и банана",
    descriptionEn: "Vitamin smoothie with spinach, apple and banana",
    descriptionUz: "Ismaloq, olma va banan bilan vitaminli smuzi",
    price: 28000,
    calories: 150,
    image: "https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400&h=300&fit=crop",
    category: "drinks",
  },
  {
    id: "10",
    name: "Фалафель с тахини соусом",
    nameEn: "Falafel Salad With Lemon-Tahini Dressing",
    nameUz: "Limon-tahini sousi bilan falafel salati",
    description: "Хрустящий фалафель с лимонно-тахини заправкой",
    descriptionEn: "Crispy falafel with lemon-tahini dressing",
    descriptionUz: "Limon-tahini sousi bilan qarsildoq falafel",
    price: 52000,
    calories: 340,
    image: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=400&h=300&fit=crop",
    category: "salads",
  },
  {
    id: "11",
    name: "Сладкий картофель и кейл",
    nameEn: "Sweet Potato, Kale & Chicken Salad With Peanut",
    nameUz: "Shirin kartoshka, keyl va yeryong'oqli tovuq salati",
    description: "Питательный салат из сладкого картофеля с кейлом",
    descriptionEn: "Nutritious sweet potato and kale salad",
    descriptionUz: "Shirin kartoshka va keyldan ozuqaviy salat",
    price: 55000,
    calories: 390,
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=400&h=300&fit=crop",
    category: "salads",
  },
  {
    id: "12",
    name: "Детокс вода с ягодами",
    nameEn: "Berry Detox Water",
    nameUz: "Rezavorli detoks suvi",
    description: "Освежающая детокс вода с лесными ягодами",
    descriptionEn: "Refreshing detox water with wild berries",
    descriptionUz: "O'rmon rezavorlari bilan tetiklantiruvchi detoks suvi",
    price: 18000,
    calories: 45,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop",
    category: "drinks",
  },
];
